version: '3.5'

networks:
  warper-network:
    name: warper-network
    driver: bridge

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      device: /home/ajjig/inception/data
      o: bind
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      device: /home/ajjig/inception/wordpress
      o: bind

services:

  mariadb:

    container_name: mariadb

    networks:
      - warper-network

    build: ./requirements/mariadb

    env_file:
      - .env

    volumes:
      - db:/var/lib/mysql

    restart: unless-stopped

  wordpress:

    container_name: wordpress

    build: ./requirements/wordpress

    networks:
      - warper-network

    ports:
      - '9000:9000'

    volumes:
      - wp:/var/www/html

    env_file:
      - .env

    depends_on:
      - mariadb

    restart: unless-stopped

  nginx:

    container_name: nginx

    build: ./requirements/nginx

    networks:
      - warper-network

    ports:
      - '443:443'

    volumes:
      - wp:/var/www/html

    depends_on:
      - wordpress

    restart: unless-stopped
