CREATE DATABASE IF NOT EXISTS wpdb ;
CREATE USER IF NOT EXISTS 'majjig'@'%' IDENTIFIED BY 'majjig@@A1' ;
GRANT ALL PRIVILEGES ON wpdb.* TO 'majjig'@'%' ;
FLUSH PRIVILEGES ;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'the-su-majjig@@A1' ;
